// generated by scripts/build-assets.ts, do not edit
// Where each clip lies in its assets/build/<file>: offsets count from the first pixel byte.

export type AtlasClip = {
  readonly frames: number
  readonly width: number
  readonly height: number
  readonly offset: number
  readonly anchorX: number
  readonly anchorY: number
  readonly frameMs: number
}

export type AtlasEntry = { readonly file: string; readonly clips: Readonly<Record<string, AtlasClip>>; readonly groundY?: number }

export const ATLAS = {
  'arrow': {
    file: 'arrow.bin',
    clips: {
      move: { frames: 2, width: 22, height: 3, offset: 0, anchorX: 10, anchorY: 1, frameMs: 100 },
    },
  },
  'bg-cave': {
    file: 'bg-cave.bin',
    groundY: 80,
    clips: {
      scene: { frames: 1, width: 384, height: 88, offset: 0, anchorX: 0, anchorY: 80, frameMs: 100 },
    },
  },
  'bg-dead-forest': {
    file: 'bg-dead-forest.bin',
    groundY: 80,
    clips: {
      scene: { frames: 1, width: 384, height: 88, offset: 0, anchorX: 0, anchorY: 80, frameMs: 100 },
    },
  },
  'bg-forest': {
    file: 'bg-forest.bin',
    groundY: 80,
    clips: {
      scene: { frames: 1, width: 384, height: 88, offset: 0, anchorX: 0, anchorY: 80, frameMs: 100 },
    },
  },
  'bg-plains': {
    file: 'bg-plains.bin',
    groundY: 80,
    clips: {
      scene: { frames: 1, width: 384, height: 88, offset: 0, anchorX: 0, anchorY: 80, frameMs: 100 },
    },
  },
  'bg-snowy-mountains': {
    file: 'bg-snowy-mountains.bin',
    groundY: 82,
    clips: {
      scene: { frames: 1, width: 384, height: 88, offset: 0, anchorX: 0, anchorY: 82, frameMs: 100 },
    },
  },
  'evil-wizard': {
    file: 'evil-wizard.bin',
    clips: {
      idle: { frames: 8, width: 35, height: 58, offset: 0, anchorX: 12, anchorY: 55, frameMs: 100 },
      run: { frames: 8, width: 52, height: 68, offset: 16240, anchorX: 21, anchorY: 66, frameMs: 100 },
      attack: { frames: 8, width: 81, height: 50, offset: 44528, anchorX: 63, anchorY: 48, frameMs: 100 },
      hit: { frames: 4, width: 42, height: 55, offset: 76928, anchorX: 14, anchorY: 54, frameMs: 100 },
      death: { frames: 5, width: 52, height: 58, offset: 86168, anchorX: 27, anchorY: 55, frameMs: 100 },
    },
  },
  'evil-wizard-2': {
    file: 'evil-wizard-2.bin',
    clips: {
      idle: { frames: 8, width: 29, height: 52, offset: 0, anchorX: 20, anchorY: 51, frameMs: 100 },
      run: { frames: 8, width: 34, height: 34, offset: 12064, anchorX: 17, anchorY: 33, frameMs: 100 },
      attack: { frames: 8, width: 81, height: 71, offset: 21312, anchorX: 55, anchorY: 70, frameMs: 100 },
      hit: { frames: 3, width: 22, height: 44, offset: 67320, anchorX: 13, anchorY: 43, frameMs: 100 },
      death: { frames: 7, width: 53, height: 60, offset: 70224, anchorX: 44, anchorY: 59, frameMs: 100 },
    },
  },
  'evil-wizard-3': {
    file: 'evil-wizard-3.bin',
    clips: {
      idle: { frames: 10, width: 37, height: 53, offset: 0, anchorX: 22, anchorY: 52, frameMs: 100 },
      run: { frames: 8, width: 45, height: 50, offset: 19610, anchorX: 25, anchorY: 49, frameMs: 100 },
      attack: { frames: 13, width: 88, height: 66, offset: 37610, anchorX: 66, anchorY: 65, frameMs: 100 },
      hit: { frames: 3, width: 37, height: 53, offset: 113114, anchorX: 18, anchorY: 52, frameMs: 100 },
      death: { frames: 18, width: 44, height: 57, offset: 118997, anchorX: 23, anchorY: 56, frameMs: 100 },
    },
  },
  'flying-eye': {
    file: 'flying-eye.bin',
    clips: {
      idle: { frames: 8, width: 42, height: 33, offset: 0, anchorX: 20, anchorY: 31, frameMs: 100 },
      run: { frames: 8, width: 42, height: 33, offset: 11088, anchorX: 20, anchorY: 31, frameMs: 100 },
      attack: { frames: 8, width: 45, height: 31, offset: 22176, anchorX: 20, anchorY: 30, frameMs: 100 },
      hit: { frames: 4, width: 41, height: 33, offset: 33336, anchorX: 20, anchorY: 30, frameMs: 100 },
      death: { frames: 4, width: 56, height: 40, offset: 38748, anchorX: 28, anchorY: 30, frameMs: 100 },
    },
  },
  'goblin': {
    file: 'goblin.bin',
    clips: {
      idle: { frames: 4, width: 33, height: 36, offset: 0, anchorX: 18, anchorY: 35, frameMs: 100 },
      run: { frames: 8, width: 38, height: 38, offset: 4752, anchorX: 21, anchorY: 37, frameMs: 100 },
      attack: { frames: 8, width: 88, height: 46, offset: 16304, anchorX: 46, anchorY: 45, frameMs: 100 },
      hit: { frames: 4, width: 42, height: 37, offset: 48688, anchorX: 23, anchorY: 36, frameMs: 100 },
      death: { frames: 4, width: 52, height: 39, offset: 54904, anchorX: 36, anchorY: 38, frameMs: 100 },
    },
  },
  'hero-knight': {
    file: 'hero-knight.bin',
    clips: {
      idle: { frames: 11, width: 47, height: 51, offset: 0, anchorX: 23, anchorY: 50, frameMs: 100 },
      run: { frames: 8, width: 44, height: 57, offset: 26367, anchorX: 26, anchorY: 55, frameMs: 100 },
      attack: { frames: 7, width: 72, height: 70, offset: 46431, anchorX: 38, anchorY: 69, frameMs: 100 },
      hit: { frames: 4, width: 54, height: 51, offset: 81711, anchorX: 30, anchorY: 50, frameMs: 100 },
      death: { frames: 11, width: 80, height: 56, offset: 92727, anchorX: 23, anchorY: 55, frameMs: 100 },
    },
  },
  'huntress': {
    file: 'huntress.bin',
    clips: {
      idle: { frames: 10, width: 32, height: 36, offset: 0, anchorX: 10, anchorY: 35, frameMs: 100 },
      run: { frames: 8, width: 35, height: 39, offset: 11520, anchorX: 12, anchorY: 38, frameMs: 100 },
      attack: { frames: 6, width: 45, height: 45, offset: 22440, anchorX: 9, anchorY: 44, frameMs: 100 },
      hit: { frames: 3, width: 30, height: 40, offset: 34590, anchorX: 9, anchorY: 39, frameMs: 100 },
      death: { frames: 10, width: 63, height: 34, offset: 38190, anchorX: 9, anchorY: 33, frameMs: 100 },
    },
  },
  'mushroom': {
    file: 'mushroom.bin',
    clips: {
      idle: { frames: 4, width: 23, height: 37, offset: 0, anchorX: 12, anchorY: 36, frameMs: 100 },
      run: { frames: 8, width: 26, height: 39, offset: 3404, anchorX: 13, anchorY: 38, frameMs: 100 },
      attack: { frames: 8, width: 64, height: 45, offset: 11516, anchorX: 40, anchorY: 44, frameMs: 100 },
      hit: { frames: 4, width: 43, height: 43, offset: 34556, anchorX: 12, anchorY: 42, frameMs: 100 },
      death: { frames: 4, width: 28, height: 37, offset: 41952, anchorX: 17, anchorY: 36, frameMs: 100 },
    },
  },
  'orb': {
    file: 'orb.bin',
    clips: {
      move: { frames: 4, width: 30, height: 11, offset: 0, anchorX: 14, anchorY: 5, frameMs: 100 },
    },
  },
  'skeleton': {
    file: 'skeleton.bin',
    clips: {
      idle: { frames: 4, width: 45, height: 51, offset: 0, anchorX: 26, anchorY: 50, frameMs: 100 },
      run: { frames: 4, width: 45, height: 51, offset: 9180, anchorX: 26, anchorY: 50, frameMs: 100 },
      attack: { frames: 8, width: 95, height: 57, offset: 18360, anchorX: 69, anchorY: 56, frameMs: 100 },
      hit: { frames: 4, width: 55, height: 53, offset: 61680, anchorX: 26, anchorY: 52, frameMs: 100 },
      death: { frames: 4, width: 56, height: 53, offset: 73340, anchorX: 29, anchorY: 50, frameMs: 100 },
    },
  },
  'wizard': {
    file: 'wizard.bin',
    clips: {
      idle: { frames: 6, width: 29, height: 43, offset: 0, anchorX: 10, anchorY: 42, frameMs: 100 },
      run: { frames: 8, width: 38, height: 40, offset: 7482, anchorX: 15, anchorY: 39, frameMs: 100 },
      attack: { frames: 8, width: 84, height: 68, offset: 19642, anchorX: 29, anchorY: 67, frameMs: 100 },
      hit: { frames: 4, width: 44, height: 43, offset: 65338, anchorX: 17, anchorY: 42, frameMs: 100 },
      death: { frames: 7, width: 53, height: 51, offset: 72906, anchorX: 16, anchorY: 50, frameMs: 100 },
    },
  },
} as const satisfies Record<string, AtlasEntry>

export type AtlasId = keyof typeof ATLAS
